# Generated by Django 3.2.4 on 2021-06-25 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 6, 33, 805551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submits',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 10, 6, 33, 805551, tzinfo=utc)),
        ),
    ]
