# Generated by Django 3.2.4 on 2021-06-22 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name ')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name ')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('affiliation', models.CharField(max_length=100, verbose_name='Name of your organization')),
                ('role', models.CharField(choices=[(None, 'Select your role'), ('Student', 'Student'), ('PhD Student', 'PhD Student'), ('Faculty Member', 'Faculty Member'), ('International Delegates', 'International Delegates'), ('Industry Person', 'Industry Person'), ('Academician', 'Academician'), ('PhD Scholar', 'PhD Scholar')], max_length=30, null=True, verbose_name='Primary role in organization')),
                ('degree', models.CharField(choices=[(None, 'Select your degree'), ('Undergraduate', 'Undergraduate'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Candidate of Sciences', 'Candidate of Sciences'), ('Doctor of Sciences', 'Doctor of Sciences')], max_length=30, null=True, verbose_name='Degree')),
                ('Conf_Role', models.CharField(choices=[(None, 'Select your role'), ('Author', 'Author'), ('Reviewer', 'Reviewer'), ('Chair', 'Chair')], max_length=30, null=True, verbose_name='Conference Role')),
                ('preferred_language', models.CharField(choices=[('ENG', 'English')], default='ENG', max_length=3)),
                ('is_Author', models.BooleanField(blank=True, default=False)),
                ('is_Chair', models.BooleanField(blank=True, default=False)),
                ('is_Reviewer', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
