# Generated by Django 3.2.4 on 2021-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_Author',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_Chair',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_Reviewer',
            field=models.BooleanField(blank=True),
        ),
    ]
