# Generated by Django 3.2.4 on 2021-06-25 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210625_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submits',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
