# Generated by Django 3.2.4 on 2021-06-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210625_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submits',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.paper'),
        ),
    ]
