# Generated by Django 3.2.4 on 2021-06-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_submits_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submits',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.paper'),
        ),
    ]
