# Generated by Django 3.2.4 on 2021-06-20 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Conference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=25)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instruction_For_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patrons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patron_Name', models.CharField(max_length=50)),
                ('Patron_Position', models.CharField(max_length=50)),
                ('work_position', models.CharField(max_length=50)),
                ('About_Patron', models.TextField(max_length=400)),
                ('Patron_Image', models.ImageField(upload_to='')),
                ('FB_link', models.CharField(blank=True, max_length=300)),
                ('tweeter_link', models.CharField(blank=True, max_length=300)),
                ('insta_link', models.CharField(blank=True, max_length=300)),
                ('personal_link', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=80)),
                ('hero_title', models.CharField(max_length=80)),
                ('hero_subtitle', models.CharField(max_length=120)),
                ('footer_contact_no', models.CharField(max_length=13)),
                ('footer_contact_mail', models.EmailField(max_length=254)),
                ('footer_FB_link', models.CharField(blank=True, max_length=500)),
                ('footer_tweeter_link', models.CharField(blank=True, max_length=500)),
                ('footer_insta_link', models.CharField(blank=True, max_length=500)),
                ('footer_gleplus_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speaker_Name', models.CharField(max_length=50)),
                ('Speaker_Position', models.CharField(max_length=50)),
                ('About_speaker', models.TextField(max_length=400)),
                ('Speaker_Image', models.ImageField(upload_to='images/speaker')),
                ('FB_link', models.CharField(blank=True, max_length=300)),
                ('tweeter_link', models.CharField(blank=True, max_length=300)),
                ('insta_link', models.CharField(blank=True, max_length=300)),
                ('personal_link', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sponcer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Sponcer_logo', models.ImageField(upload_to='')),
                ('About_sponcers', models.TextField(blank=True)),
                ('Sponcer_contact_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=80)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7000)),
                ('Specification', models.TextField(blank=True)),
                ('payment_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=25)),
                ('Last_Name', models.CharField(blank=True, max_length=25)),
                ('Profile_type', models.CharField(choices=[('Student', 'Student'), ('International delegates/Industry Person', 'International delegates/Industry Person'), ('Acadmician/PHD scholar', 'Acadmician/PHD scholar')], default=False, max_length=50)),
                ('Bio', models.TextField(max_length=200)),
                ('is_Author', models.BooleanField(blank=True, verbose_name='is Author')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
