# Generated by Django 3.2.4 on 2021-06-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Profile_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_Author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
