# Generated by Django 3.2.4 on 2021-06-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakers',
            old_name='insta_link',
            new_name='linkdin_link',
        ),
    ]
