# Generated by Django 3.2.4 on 2021-06-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_rename_insta_link_speakers_linkdin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrons',
            name='Patron_Image',
            field=models.ImageField(upload_to='images/patrons'),
        ),
        migrations.AlterField(
            model_name='sponcer',
            name='Sponcer_logo',
            field=models.ImageField(upload_to='images/sponcer'),
        ),
    ]
